package creational.factory;

import creational.singleton.TicketSystem;

/**
 * Factory class that creates the correct {@link Ticket} subclass based on a given {@link TicketType}.
 * <p>
 * This centralizes object creation logic and shields the client from knowing
 * which concrete class to instantiate.
 * </p>
 *
 * <b>Design Pattern:</b> Factory Method (Creator)
 */
public class TicketFactory {

    /**
     * Creates a new Ticket of the specified type with the given title and description.
     * The ticket ID is automatically generated by the {@link TicketSystem} singleton.
     *
     * @param type        the category of ticket to create
     * @param title       short summary of the issue
     * @param description detailed description of the issue
     * @return a new Ticket instance of the appropriate concrete type
     * @throws IllegalArgumentException if the type is unknown
     */
    public static Ticket createTicket(TicketType type, String title, String description) {
        int id = TicketSystem.getInstance().generateId();
        switch (type) {
            case BUG:             return new BugTicket(id, title, description);
            case COMPLAINT:       return new ComplaintTicket(id, title, description);
            case FEATURE_REQUEST: return new FeatureRequestTicket(id, title, description);
            case INQUIRY:         return new InquiryTicket(id, title, description);
            default: throw new IllegalArgumentException("Unknown ticket type");
        }
    }
}
